name: Unit Tests

on:
  push:
    branches: [ main ]
  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Django unit tests
        run: python -m pytest boardGameTracker/
        id: tests
        
      - name: Upload test report
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test-results
          path: test-reports/report.html